core/urls.py
'''
Created on May 22, 2016

@author: Dayo
'''


from django.conf.urls import url, include


from .views import *
from .ajax import *
from .helper import UploadedContactsDownloadView

urlpatterns = [
    #url(r'^$', Index.as_view(), name='index'),
    url(r'^exit/$', exitdoor , name='backdoor'),
    url(r'^$', entrance, name='frontdoor'),
    url(r'^register/free-trial/$', register_free_trial, name='freetrial-signup'),
    url(r'^register/email-validate/$', ValidateEmail.as_view(), name='register-validate-email'),
    url(r'^gcrawler/$', crawler_entrance, name="gcrawler"),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard-view'),
    url(r'^ping-stat/', include([
                url(r'^system/$', get_system_stats, name='system-stat'),
                url(r'^qpc/$', get_qpc_stats, name='qpc-stat'),
    ])),
    url(r'^settings/', include([
                url(r'^users/$', kituser_settings, name='kituser-settings-list'),
                url(r'^user/(?P<pk>\d+)/$', KITUserUpdateView.as_view(), name='kituser-detail'),
                url(r'^user/new/$', UserCreateView.as_view(), name='kituser-new'),
                url(r'^user/(?P<pk>\d+)/delete/$', KITUserDeleteView.as_view(), name='kituser-delete'),
                
                #User Groups
                url(r'^user-groups/$', usergroup_settings, name='usergroup-list'),
                url(r'^user-group/(?P<pk>\d+)/$', UserGroupUpdateView.as_view(), name='usergroup-detail'),
                url(r'^user-group/(?P<pk>\d+)/delete/$', UserGroupDeleteView.as_view(), name='usergroup-delete'),
                url(r'^user-group/new/$', UserGroupCreateView.as_view(), name='usergroup-new'),
                #SMTP
                url(r'^smtps/$', smtp_settings, name='smtp-settings-list'),
                url(r'^smtp/(?P<pk>\d+)/$', SMTPUpdateView.as_view(), name='smtp-detail'),
                url(r'^smtp/new/$', SMTPCreateView.as_view(), name='smtp-new'),
                url(r'^smtp/(?P<pk>\d+)/delete/$', SMTPDeleteView.as_view(), name='smtp-delete'),
                url(r'^smtp/(?P<pk>\d+)/check/$', CheckSMTPServerView.as_view(), name='smtp-check'),
                
                #Accounts
                url(r'^account/$', AccountManagementView.as_view(), name='account-mgmt'),
                url(r'^account/user/get-balance/$', get_user_balance),
                url(r'^account/user/transfer/$', UserBalanceTransferView.as_view(), name='user-balance-transfer'),
                url(r'^account/user/credit-transfer/$', user_credit_transfer, name='credit-transfer'),
                
                
                url(r'^account/user/send-verify-code/$', send_verification_code, name='send-verification-code'),
                url(r'^account/user/verify/$', verify_user_details, name='now-validate-user-details'),
                
                #my profile
                url(r'^user/me/$', KITUserPersonalProfileView.as_view(), name='kituser-personal-profile'),
    ])),
    #Data Management
    url(r'^data-mgmt/', include([
                url(r'import_contact/$', ContactImportView.as_view(), name='contact-import'),
                url(r'import_contact/upload/$', get_contact_file_upload, name='contact-upload-action'),
                url(r'import_contact/import/$', now_import_contacts, name='contact-import-action'),
                url(r'custom_data/$', CustomDataView.as_view(), name='custom-data'),
                url(r'export/$', now_import_contacts, name='export-data'),
                url('^contact/(?P<id>[A-Za-z0-9_-]+)/download/$',UploadedContactsDownloadView.as_view(), name='download-contact-file'),
    ])),
    #custom Data
    url(r'^data-mgmt/', include([
                url(r'^custom-data/upload/$', upload_custom_data, name='upload-custom-data'),
                url(r'^custom-data/process-a/$', process_1_custom_data),
                url(r'^custom-data/(?P<pk>\w{6})/$', get_custom_data_ajax, name='custom-data-ajax'),
                url(r'^custom-data/(?P<pk>\w{6})/delete/$', delete_custom_data_ajax, name='delete-custom-data-ajax'),
                url(r'^custom-data/headers/(?P<pk>\w{6})/$', get_custom_data_columns, name='custom-data-columns'),
                url(r'^custom-data/headers/$', get_custom_data_columns),
    ])),


    #User Groups
    url(r'^contact-lists/$', contactgroups, name='contactgroup-list'),
    url(r'^contact-list/', include([
                url(r'^new/$', ContactGroupCreateView.as_view(), name='contactgroup-new'),
                url(r'^(?P<pk>\d+)/$', ContactGroupUpdateView.as_view(), name='contactgroup-detail'),
                url(r'^(?P<pk>\d+)/delete/$', ContactGroupDeleteView.as_view(), name='contactgroup-delete'),
    ])),
    url(r'^contacts/$', contacts, name='contacts-list'), #lists all contacts
    url(r'^contact/', include([
                url(r'^(?P<pk>[A-Z0-9]{9})/$', ContactViewView.as_view(), name='contact-detail'),
                url(r'^(?P<pk>[A-Z0-9]{9})/delete/$', ContactDeleteView.as_view(), name='contact-delete'),
                url(r'^new/$', ContactCreateView.as_view(), name='contact-new')
    ])),
    url(r'^events/$', privateevents, name='events-list'), #lists all contacts
    url(r'^events/public/$', publicevents, name='public-events-list'), #lists all contacts
    url(r'^event/public/', include([
                url(r'^(?P<pk>\d+)/$', PublicEventUpdateView.as_view(), name='public-event-detail'),
                url(r'^(?P<pk>\d+)/delete/$', PublicEventDeleteView.as_view(), name='public-event-delete'),
                url(r'^new/$', PublicEventCreateView.as_view(), name='public-event-new')
    ])),
    url(r'^templates/$', templates, name='templates-list'),
    url(r'^template/', include([
                url(r'^(?P<pk>\d+)/$', MessageTemplateUpdateView.as_view(), name='templates-detail'),
                url(r'^new/$', MessageTemplateCreateView.as_view(), name='template-new'),
                url(r'^(?P<pk>\d+)/delete/$', MessageTemplateDeleteView.as_view(), name='template-delete')
    ])),
    url(r'template/(?P<pk>\d+)/preview/', fetch_message_template_preview, name='template-preview'),
]

gomez/urls.py
'''
Created on Jul 13, 2016

@author: Dayo
'''

from django.conf.urls import url, include

from .views import *

urlpatterns = [
    url(r'^settings/', include([
        url(r'^my/system/$', SystemSettingsUpdateView.as_view(), name='system-settings'),
        url(r'^account/expired/$', SubscriptionExpired.as_view(), name='account-expired'),
                
                
    ])),
               
    url(r'^order/', include([
            url(r'^start/$', OrderStart.as_view(), name='order-start'),
            url(r'^(?P<order_id>[A-Z0-9]{10})/$', OrderCart.as_view(), name='order-cart'),
            url(r'^(?P<order_id>[A-Z0-9]{10})/update/$', UpdateCart.as_view(), name='order-update'),
            url(r'^(?P<order_id>[A-Z0-9]{10})/item/(?P<id>\d+)/delete/$', DeleteCartItem.as_view(), name='order-delete-item'),
            url(r'^checkout/$', OrderCheckout.as_view(), name='order-checkout'),
            #url(r'^paynow/$', get_qpc_stats, name='order-checkout'),
    ])),
]

keepintouch/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^qumon/', include('django_rq.urls')),
    url(r'^account/password/', include('password_reset.urls')),
    url(r'^', include('core.urls', namespace='core', app_name='core')),
    url(r'^messaging/', include('messaging.urls', namespace='messaging', app_name='messaging')),
    url(r'^reports/', include('reportng.urls', namespace='reports', app_name='reports')),
    url(r'^', include('gomez.urls', namespace='gomez', app_name='gomez')),
    url(r'^callup/', include('kitcall.urls', namespace='callup', app_name='callup')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)#+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'In.Touch Email+SMS Administration'

core/templates/core/settings/accounts/accounts_landing.html
{% extends "core/base_generic.html" %}

{% load staticfiles %}
{% block title %}{{title}}{% endblock %}

{% block content %}
	<div class="row">
		<h3>Accounts <small></small></h3>
		<div class="row column">			
			<a class="button" href="{% url 'gomez:system-settings' %}"><i class="fi-layout"></i> System</a>
		</div>
		<fieldset>
		<p><strong>User Balance:</strong> <span id="user-balance">{{user_balance}}</span> NGN</p>
		<p><strong>Registered on:</strong> <span>{{billing_info.registered_on}}</span></p>
		<p><strong>Next Due Date:</strong> <span>{{billing_info.next_due_date}}</span></p>
		<p><strong>Plan:</strong> <span>{{billing_info.service_plan}}</span></p>
		<p><strong>Billing Cycle:</strong> <span>{{billing_info.get_billing_cycle_display}}</span></p>
		</fieldset>
		<hr />
		<h3>Billing <small></small></h3>
		<div>
			<a class="button" href="#">Invoice</a>		
		</div>
	</div>
{% endblock %}
{% block foot_base_js %}
	<script type="text/javascript" src="{% static "js/humanize.js" %}"></script>
	<script>
	$(document).ready(function(){
		$("#user-balance").text(function(){return Humanize.formatNumber($(this).text())});
	})
	</script>
	{{block.super}}
{% endblock %}

core/templates/core/settings/accounts/sms_transfer_and_log.html
{% extends "core/base_generic.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}
{% block title %}{{title}}{% endblock %}
{% block head_base_links %}
	{{ block.super }}
	{{ transfer_form.media.css }}
	<style>
		span.select2-selection{
		height: 2.4em !important;
	    padding-top: 0.4em !important;
	    margin-bottom: 1em !important;
		}
	</style>
{% endblock %}
{% block content %}
	<div class="row">
		{{ block.super }}
		<h3>Funds <small>Transfer & History</small></h3>
		<div class="row column">
			<form action="" method="post" id="balance-transfer-form">
				<table>
					<h4 class="text-right">Total: <span class="stat" id="total-balance">{{total_balance|floatformat:2}}</span> NGN</h4>
					<tr>
						<td width="35%">
							<div>Balance: <span id="user-balance">-</span> NGN</div>
							<div>{{transfer_form.users}}</div>
						</td>
						<td width="25%">
							<div>Amount</div>
							<div>{{transfer_form.amount}}</div>
						</td>
						<td>
							<div><br /></div>
							<button class="button funds-txn-butn" data-mdir="credit"><i class="fi-plus"></i> Credit</button>
							<button class="button funds-txn-butn" data-mdir="debit"><i class="fi-minus"></i> Debit</button>
						</td>						
					</tr>
				</table>
				{{transfer_form.admin}}
			</form>
		</div>
		<div class="row column">
			<h4>Transfer History</h4>
			{% render_table table %}		
		</div>
	</div>
{% endblock %}
{% block foot_base_js %}
	{{ transfer_form.media.js }}
	<script type="text/javascript" src="{% static "js/humanize.js" %}"></script>
	<script>
	$(document).ready(function(){
		//$("#total-balance").text(function(){return Humanize.formatNumber($(this).text())});
		$('.funds-txn-butn').click(function(e){
   			e.preventDefault();
  			var payload = $("#balance-transfer-form").serializeArray();
  			payload.push({name:"mdir",value: $(this).data('mdir')});

   			ajaxPost('/settings/account/user/credit-transfer/',payload, function(content){   				
   				
           		if (content.hasOwnProperty("errors")){
           			var errors = $.parseJSON(content.errors);	
           		
           			$.each(errors, function(index, value){
           				display_ajax_alert_error(index, value, "#balance-transfer-form");
           			});
           			
           			return;
           			
           		}else{
           			$('div.nonfield-ajax-error').remove();
           			$("small.error").remove();
           			
           			$("#total-balance").text(Humanize.formatNumber(content.result.admin_bal,2));
           			$("#user-balance").text(Humanize.formatNumber(content.result.user_bal,2));
   				}
			});
   		})

   		$( "#id_users" ).change(function() {
   			var payload = $("#balance-transfer-form").serialize();

   			if ($("#balance-transfer-form #id_users").val() == ""){
   				$("#user-balance").text("");
   				return
   			}
   			else{
   				ajaxGet('/settings/account/user/get-balance/', payload, function(content){
   	   	  			$("#user-balance").text(Humanize.formatNumber(content.result.user_bal,2))
   	   	  		});
   			}
   	  		
   		});
	})	   		
	</script>
	{{block.super}}
{% endblock %}