core/urls.py
'''
Created on May 22, 2016

@author: Dayo
'''


from django.conf.urls import url, include


from .views import *
from .ajax import *
from .helper import UploadedContactsDownloadView

urlpatterns = [
    #url(r'^$', Index.as_view(), name='index'),
    url(r'^exit/$', exitdoor , name='backdoor'),
    url(r'^$', entrance, name='frontdoor'),
    url(r'^register/free-trial/$', register_free_trial, name='freetrial-signup'),
    url(r'^register/email-validate/$', ValidateEmail.as_view(), name='register-validate-email'),
    url(r'^gcrawler/$', crawler_entrance, name="gcrawler"),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard-view'),
    url(r'^ping-stat/', include([
                url(r'^system/$', get_system_stats, name='system-stat'),
                url(r'^qpc/$', get_qpc_stats, name='qpc-stat'),
    ])),
    url(r'^settings/', include([
                url(r'^users/$', kituser_settings, name='kituser-settings-list'),
                url(r'^user/(?P<pk>\d+)/$', KITUserUpdateView.as_view(), name='kituser-detail'),
                url(r'^user/new/$', UserCreateView.as_view(), name='kituser-new'),
                url(r'^user/(?P<pk>\d+)/delete/$', KITUserDeleteView.as_view(), name='kituser-delete'),
                
                #User Groups
                url(r'^user-groups/$', usergroup_settings, name='usergroup-list'),
                url(r'^user-group/(?P<pk>\d+)/$', UserGroupUpdateView.as_view(), name='usergroup-detail'),
                url(r'^user-group/(?P<pk>\d+)/delete/$', UserGroupDeleteView.as_view(), name='usergroup-delete'),
                url(r'^user-group/new/$', UserGroupCreateView.as_view(), name='usergroup-new'),
                #SMTP
                url(r'^smtps/$', smtp_settings, name='smtp-settings-list'),
                url(r'^smtp/(?P<pk>\d+)/$', SMTPUpdateView.as_view(), name='smtp-detail'),
                url(r'^smtp/new/$', SMTPCreateView.as_view(), name='smtp-new'),
                url(r'^smtp/(?P<pk>\d+)/delete/$', SMTPDeleteView.as_view(), name='smtp-delete'),
                url(r'^smtp/(?P<pk>\d+)/check/$', CheckSMTPServerView.as_view(), name='smtp-check'),
                
                #Accounts
                url(r'^account/$', AccountManagementView.as_view(), name='account-mgmt'),
                url(r'^account/user/get-balance/$', get_user_balance),
                url(r'^account/user/transfer/$', UserBalanceTransferView.as_view(), name='user-balance-transfer'),
                url(r'^account/user/credit-transfer/$', user_credit_transfer, name='credit-transfer'),
                
                
                url(r'^account/user/send-verify-code/$', send_verification_code, name='send-verification-code'),
                url(r'^account/user/verify/$', verify_user_details, name='now-validate-user-details'),
                
                #my profile
                url(r'^user/me/$', KITUserPersonalProfileView.as_view(), name='kituser-personal-profile'),
    ])),
    #Data Management
    url(r'^data-mgmt/', include([
                url(r'import_contact/$', ContactImportView.as_view(), name='contact-import'),
                url(r'import_contact/upload/$', get_contact_file_upload, name='contact-upload-action'),
                url(r'import_contact/import/$', now_import_contacts, name='contact-import-action'),
                url(r'custom_data/$', CustomDataView.as_view(), name='custom-data'),
                url(r'export/$', now_import_contacts, name='export-data'),
                url('^contact/(?P<id>[A-Za-z0-9_-]+)/download/$',UploadedContactsDownloadView.as_view(), name='download-contact-file'),
    ])),
    #custom Data
    url(r'^data-mgmt/', include([
                url(r'^custom-data/upload/$', upload_custom_data, name='upload-custom-data'),
                url(r'^custom-data/process-a/$', process_1_custom_data),
                url(r'^custom-data/(?P<pk>\w{6})/$', get_custom_data_ajax, name='custom-data-ajax'),
                url(r'^custom-data/(?P<pk>\w{6})/delete/$', delete_custom_data_ajax, name='delete-custom-data-ajax'),
                url(r'^custom-data/headers/(?P<pk>\w{6})/$', get_custom_data_columns, name='custom-data-columns'),
                url(r'^custom-data/headers/$', get_custom_data_columns),
    ])),


    #User Groups
    url(r'^contact-lists/$', contactgroups, name='contactgroup-list'),
    url(r'^contact-list/', include([
                url(r'^new/$', ContactGroupCreateView.as_view(), name='contactgroup-new'),
                url(r'^(?P<pk>\d+)/$', ContactGroupUpdateView.as_view(), name='contactgroup-detail'),
                url(r'^(?P<pk>\d+)/delete/$', ContactGroupDeleteView.as_view(), name='contactgroup-delete'),
    ])),
    url(r'^contacts/$', contacts, name='contacts-list'), #lists all contacts
    url(r'^contact/', include([
                url(r'^(?P<pk>[A-Z0-9]{9})/$', ContactViewView.as_view(), name='contact-detail'),
                url(r'^(?P<pk>[A-Z0-9]{9})/delete/$', ContactDeleteView.as_view(), name='contact-delete'),
                url(r'^new/$', ContactCreateView.as_view(), name='contact-new')
    ])),
    url(r'^events/$', privateevents, name='events-list'), #lists all contacts
    url(r'^events/public/$', publicevents, name='public-events-list'), #lists all contacts
    url(r'^event/public/', include([
                url(r'^(?P<pk>\d+)/$', PublicEventUpdateView.as_view(), name='public-event-detail'),
                url(r'^(?P<pk>\d+)/delete/$', PublicEventDeleteView.as_view(), name='public-event-delete'),
                url(r'^new/$', PublicEventCreateView.as_view(), name='public-event-new')
    ])),
    url(r'^templates/$', templates, name='templates-list'),
    url(r'^template/', include([
                url(r'^(?P<pk>\d+)/$', MessageTemplateUpdateView.as_view(), name='templates-detail'),
                url(r'^new/$', MessageTemplateCreateView.as_view(), name='template-new'),
                url(r'^(?P<pk>\d+)/delete/$', MessageTemplateDeleteView.as_view(), name='template-delete')
    ])),
    url(r'template/(?P<pk>\d+)/preview/', fetch_message_template_preview, name='template-preview'),
]

keepintouch/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^qumon/', include('django_rq.urls')),
    url(r'^account/password/', include('password_reset.urls')),
    url(r'^', include('core.urls', namespace='core', app_name='core')),
    url(r'^messaging/', include('messaging.urls', namespace='messaging', app_name='messaging')),
    url(r'^reports/', include('reportng.urls', namespace='reports', app_name='reports')),
    url(r'^', include('gomez.urls', namespace='gomez', app_name='gomez')),
    url(r'^callup/', include('kitcall.urls', namespace='callup', app_name='callup')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)#+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'In.Touch Email+SMS Administration'

messaging/urls.py
'''
Created on Jun 10, 2016

@author: Dayo
'''


from django.conf.urls import url, include


from .views import *
from .ajax import prepare_to_send_message, send_message, run_reminder, submit_issue_fb, send_quick_sms

urlpatterns = [
    url(r'^create/success/$', StandardMessageCreateView.as_view(), name=''),
    url(r'^prepare-to-send-message/$', prepare_to_send_message, name='messages-prepare-send-message'),
    url(r'^send-message/$', send_message, name='messages-send-message'),
    url(r'^send-quick-sms/$', send_quick_sms, name='send-quick-sms'),
    url(r'^run-reminder/$', run_reminder, name='run-reminder-message'),
    url(r'^processed/messages/$', message_processed_status_view, name='messages-processed-status'),
    url(r'^queued/messages/$', message_queued_status_view, name='messages-queued-status'),
    url(r'^queued/message/(?P<mtype>ADVANCED|STANDARD)/(?P<pk>\d+)/dequeue/$', queued_message_dequeue_view, name='queued-message-dequeue'),
    
    url(r'^running/messages/$',  message_running_status_view, name='messages-running-status'),
    url(r'^running/message/REMINDER/(?P<pk>\d+)/dequeue/$', queued_message_dequeue_view, name='running-message-dequeue'),
    
    url(r'^standard/', include([
                url(r'^new/$', StandardMessageCreateView.as_view(), name='new-standard-message'),
                url(r'^draft/(?P<pk>\d+)/$', StandardMessageUpdateDraftView.as_view(), name='standard-message-draft'),
                url(r'^draft/messages/$', standard_message_draft_view, name='standard-draft-messages'),
                url(r'^message/(?P<pk>\d+)/delete/$', StandardMessageDeleteView.as_view(), name='standard-message-delete'),
                ])),
    url(r'^advanced/', include([
                url(r'^new/$', AdvancedMessageCreateView.as_view(), name='new-advanced-message'),
                url(r'^draft/(?P<pk>\d+)/$', AdvancedMessageUpdateDraftView.as_view(), name='advanced-message-draft'),
                url(r'^draft/messages/$', advanced_message_draft_view, name='advanced-draft-messages'),
                url(r'^message/(?P<pk>\d+)/delete/$', AdvancedMessageDeleteView.as_view(), name='advanced-message-delete'),
                
                ])),
    url(r'^reminder/', include([
            url(r'^new/$', ReminderCreateView.as_view(), name='new-reminder-message'),
            url(r'^draft/(?P<pk>\d+)/$', ReminderUpdateDraftView.as_view(), name='reminder-message-draft'),
            url(r'^draft/messages/$', reminder_draft_view, name='reminder-draft-messages'),
            url(r'^message/(?P<pk>\d+)/delete/$', ReminderDeleteView.as_view(), name='reminder-message-delete'),
            ])),
    url(r'^system/feedback/$', submit_issue_fb, name='system-user-feedback'),
    url(r'^failed/', include([
            url(r'^messages/$', failed_kit_messages_view, name='kit-messages-failed'),
            url(r'^message/(?P<pk>\d+)/retry/$', failed_messaging_retry, name='failed-kit-message-retry'),
            url(r'^smss/$', failed_sms_messages_view, name='sms-messages-failed'),
            url(r'^sms/(?P<pk>\d+)/retry/$', failed_sms_message_retry, name='failed-sms-message-retry'),
            url(r'^emails/$', failed_email_messages_view, name='email-messages-failed'),
            url(r'^email/(?P<pk>\d+)/retry/$', failed_email_message_retry, name='failed-email-message-retry'),
            ])),
    
]

reportng/urls.py
'''
Created on Sep 13, 2016

@author: Dayo
'''


from django.conf.urls import url, include


from .views import *
from .webhooks import *

urlpatterns = [
    #url(r'^$', Index.as_view(), name='index'),
    url(r'^sms/$', SMSReport.as_view(), name='sms-reports'),
    url(r'^email/$', EmailReport.as_view(), name='email-reports'),
    url(r'^call/$', CallReport.as_view(), name='call-reports'),
    url(r'^sms/delivery/infobip/$', infobip_sms_delivery_report_callback, name='infobip-delivery-url'),
    url(r'^email/event/sendgrid/$', sendgrid_report_callback, name='sendgrid-event-url'),
    url(r'^webhook/cdr/$', fs_call_detail_report_callback, name='fs-cdr-url'),
]

core/templates/core/access.html
{% load staticfiles %}
{% load sitegate %}
{% load google_analytics %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="google-site-verification" content="H3VLJGOuBuzxDGGUrtvu_ChfCb0vd_JgN11cyGssOrc" />
	{% google_analytics %}
	<title>Intouch - {{title}}</title>
	{% block head_base_links %}
		<link rel="stylesheet" href="{% static "css/foundation.css" %}" />
		<link rel="stylesheet" href="{% static "css/foundation-icons/foundation-icons.css" %}" />
		<link href="{% static "css/main.css" %}" rel="stylesheet">
		<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	{% endblock %}
	<style>
	label[for="id_signin_flow"]{
		display: none;
	}
	body{
		background: url({% static "images/background-app.png" %}) no-repeat center center fixed;
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;
	}
	</style>
</head>
<body>
	{% block body %}
	<div class="row column large-12" style="margin-top: 1rem;">
		<a href="#">
			<img style="vertical-align: text-bottom;" width="50" src="{% static "images/logo-100x100.png" %}" alt="Intouch Enterprise Email & SMS Suite"/>
			<h3 style="display: inline-block; line-height: 2rem">InTouch Communication Suite</h3>
		</a>
		<h4>All-in-One Enterprise Email and SMS</h4>		
	</div>
	
	<div class="row">
		<div class="column large-5 login-form">
			{% sitegate_signin_form %}
			<a href="{% url 'password_reset_recover' %}">Forgot Password</a>
		</div>
	</div>
	<div class="row columns" style="margin-top: 1rem;">
		<div class="row">Developed by <a href="http://tekartng.com" style="color: #3f3f3f; font-weight: bold;">Tekart Limited</a></div>
	</div>
	{% endblock %}
	{% block foot_base_js %}
		<script type="text/javascript" src="{% static "js/vendor/what-input.js" %}"></script>
		<script type="text/javascript" src="{% static "js/vendor/foundation.js" %}"></script>
		<script type="text/javascript" src="{% static "js/main.js" %}"></script>
	{% endblock %}
	
	<!--Start of Tawk.to Script-->
		<script type="text/javascript">
		var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
		(function(){
		var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
		s1.async=true;
		s1.src='https://embed.tawk.to/57c457eb416c00672f6343ff/default';
		s1.charset='UTF-8';
		s1.setAttribute('crossorigin','*');
		s0.parentNode.insertBefore(s1,s0);
		})();
		</script>
	<!--End of Tawk.to Script-->
</body>
</html>

core/templates/core/base_generic.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}



{% block body %}
	<div class="off-canvas-wrapper">
		<div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
			<div class="off-canvas position-left" id="offCanvas" data-off-canvas>
				<button class="close-button hide" aria-label="Close menu" type="button" data-close>
					<span aria-hidden="true">&times;</span>
				</button>
				{% block offcm %}
					{% include "core/menu.html" %}
					<div style="margin-top: 1rem; text-align: center;">
						<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
						<!-- InTouch Mobile View LSB -->
						<ins class="adsbygoogle"
						     style="display:block"
						     data-ad-client="ca-pub-8909496138809362"
						     data-ad-slot="8297188869"
						     data-ad-format="auto"></ins>
						<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
						</script>
					</div>
				{% endblock %}
			</div>
			<div class="off-canvas-content" data-off-canvas-content>
				{% block header%}
				<div class="row columns kitapp-header">
					<div class="title-bar">
						<div class="title-bar-left">
							<button class="menu-icon hide-for-large" type="button" data-toggle="offCanvas"></button>
							<span class="title-bar-title"><img width="20px" src="{%  static 'images/favicon.png' %}" /> In.Touch</span>
						</div>
						<div class="title-bar-right" id="k-user-profile-nav">
							<a href="#" id="k-user-greeting">Hi {% if user.get_full_name %}{{user.get_full_name}}{% else %}{{user.get_username}}{% endif %}</a>
							<div id="k-dropdown-content">
								<ul>
									<li>
										<div>
											Balance	
											<h5 style="margin-bottom:0; color: #000;">{{ user.kituser.kitubalance.user_balance|floatformat:2}}<span class="small"> NGN</span></h5>									
										</div>
									</li>
									<li>
										<a href="{% url 'core:kituser-personal-profile' %}"><i class="fi-sheriff-badge"></i> My Profile</a>
									</li>
									<li>
										<a href="http://intouchng.com/docs/documentation/introduction/" target="_blank"><i class="fi-page-multiple"></i> Docs</a>
									</li>
									<li>
										<a href="{% url 'core:backdoor' %}"><i class="fi-power" style="color: red"></i> Logout</a>
									</li>
								</ul>
							</div>
						</div>
						
						<span style="float: right; margin-right: 1.5rem; font-size: 1.4rem;">
							<a href="#" alt="notifications" title="Notifications"><i class="fi-rss" style="color: #fff; text-shadow: rgb(128, 128, 128) 1px 1px 0px;"></i></a>
						</span>
					</div>
				</div>
				{% endblock %}
				<div class="row columns">
					{% block container %}
						<div class="show-for-large medium-3 column">
							{% block lsb %}
								{% include "core/menu.html" %}
							{% endblock %}
							<div style="margin-top: 1rem; text-align: center;">
								<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
								<!-- Intouch LSB -->
								<ins class="adsbygoogle"
								     style="display:block"
								     data-ad-client="ca-pub-8909496138809362"
								     data-ad-slot="3649676464"
								     data-ad-format="auto"></ins>
								<script>
								(adsbygoogle = window.adsbygoogle || []).push({});
								</script>
							</div>
						</div>
						<div class="small-12 large-9 column kitapp-content clearfix">							
							{% block breadcrumbs %}
							    {% clear_breadcrumbs %}
							    {% breadcrumb_safe "<i class='fi-home'></i>" "/" %}
							{% endblock %}
							{% block content %}
								{% render_breadcrumbs %}
								{% if messages %}
								<div class="alert callout">
									{% for message in messages %}
										<p>{{ message }}</p>
									{% endfor %}
								</div>
								{% endif %}
							{% endblock %}
							<div class="row show-for-small" style="margin-top: 1rem;">
							<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
							<!-- InTouch Mobile Bottom -->
							<ins class="adsbygoogle"
							     style="display:block"
							     data-ad-client="ca-pub-8909496138809362"
							     data-ad-slot="5174305262"
							     data-ad-format="auto"></ins>
							<script>
							(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
							</div>
						</div>
					{% endblock %}
				</div>
				<div class="row footer">
					{% block footer %}
						<div class="small-12 columns"><span class="float-right">Copyright &copy; Tekart Ltd. 2016</span></div>
					{% endblock %}
				</div>
			</div>
		</div>
	</div>
	
	<div class="modal" id="loadingDiv" style="z-index: 10000;">
		<center><img style="padding-top: 21%" src="{% static 'images/spinner.svg' %}" alt="spinner"/></center>
		<center><button class="button warning" onclick="location.reload(0)">Refresh Page</button></center>
	</div>
{% endblock %}

core/templates/core/crawler_access.html
{% load staticfiles %}
{% load sitegate %}
{% load google_analytics %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="google-site-verification" content="H3VLJGOuBuzxDGGUrtvu_ChfCb0vd_JgN11cyGssOrc" />
	<title>Intouch - {{title}}</title>
	
</head>
<body>
	{% sitegate_signin_form %}
</body>
</html>

core/templates/core/email_address_confirmation.html
{% load staticfiles %}
{% load google_analytics %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Intouch - {{title}}</title>
	{% block head_base_links %}
		<link rel="stylesheet" href="{% static "css/foundation.css" %}" />
		<link rel="stylesheet" href="{% static "css/foundation-icons/foundation-icons.css" %}" />
		<link href="{% static "css/main.css" %}" rel="stylesheet">
		<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	{% endblock %}
	<style>
	body{
		background: url({% static "images/background-app.png" %}) no-repeat center center fixed;
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;
	}
	</style>
</head>
<body>
	{% block body %}
	<div class="row column large-12" style="margin-top: 1rem;">	
	</div>
	<div class="row">
		<div class="column medium-3"><p /></div>
		<div class="column small-12 medium-6">
			<div class="signup-form">
				<a href="#">
					<img style="vertical-align: text-bottom;" width="50" src="{% static "images/logo-100x100.png" %}" alt="Intouch Enterprise Email & SMS Suite"/>
					<h4 style="display: inline-block; line-height: 2rem">In.Touch Communication Suite</h4>
				</a>	
				<div style="text-align: center; margin-top:2rem;">{{validation_message}}</div>
				<div style="text-align: center; margin-top:2rem; font-size: 75%; color: orangered;">You will be redirected in <span id="countd">5</span> seconds...</div>
			</div>
		</div>
		<div class="column medium-3"><p /></div>
	</div>
	{% endblock %}
	{% block foot_base_js %}
		<script type="text/javascript" src="{% static "js/vendor/what-input.js" %}"></script>
		<script type="text/javascript" src="{% static "js/vendor/foundation.js" %}"></script>
		<script type="text/javascript" src="{% static "js/main.js" %}"></script>
		<script>
		(function () {
		    var timeLeft = 5,
		        cinterval;

		    var timeDec = function (){
		    	$('#countd').text(timeLeft);
		        if(timeLeft === 0){
		            clearInterval(cinterval);
		            window.location.replace("/");
		        }
		        timeLeft--;
		    };

		    cinterval = setInterval(timeDec, 1000);
		})();
		
		</script>
	{% endblock %}
	{% google_analytics %}
</body>
</html>

core/templates/core/menu.html
{% load activeurl %}

{% activeurl %}
	<ul class="vertical menu kitapp-lsm" data-accordion-menu>
		{% if request.user.kituser.is_admin %}
			<li><a href="{% url 'core:dashboard-view' %}"><i class="fi-home"></i> Dashboard</a></li>
		{% endif %}
		<li><a href="#"><i class="fi-telephone"></i> Phone</a></li>
		<li class="kparnt">
			<a href="#"><i class="fi-address-book"></i> Contact</a>
			<ul class="menu vertical nested is-active">
				<li><a href="{% url 'core:contacts-list' %}">Contacts</a></li>
				<li><a href="{% url 'core:contactgroup-list' %}">Lists</a></li>
			</ul>
		</li>
		
		
		<li class="kparnt">
			<a href="#"><i class="fi-mail"></i> Messaging</a>
			<ul class="menu vertical nested is-active">
				<li><a href="#"><i class=""></i>Inbox</a></li>
				<li><a href="{% url 'messaging:new-standard-message' %}">Standard</a></li>
				<li><a href="{% url 'messaging:new-advanced-message' %}">Advanced</a></li>
				{% if perms.messaging.add_remindermessaging %}
				<li><a href="{% url 'messaging:new-reminder-message' %}">Reminder</a></li>
				{% endif %}
				<hr style="padding: 0 1rem">
				<li class="kitapp-lsm-submenu"><a href="{% url 'messaging:standard-draft-messages' %}"><i class="fi-folder"></i> Drafts</a></li>
				<li class="kitapp-lsm-submenu"><a href="{% url 'messaging:messages-queued-status' %}"><i class="fi-database"></i> Queued</a></li>
				{% if perms.messaging.add_remindermessaging %}
				<li class="kitapp-lsm-submenu"><a href="{% url 'messaging:messages-running-status' %}"><i class="fi-foot"></i> Running Reminders</a></li>
				{% endif %}
				<li class="kitapp-lsm-submenu" ><a href="{% url 'messaging:messages-processed-status' %}"><i class="fi-checkbox"></i> Processed</a></li>
				<li class="kitapp-lsm-submenu" ><a href="{% url 'messaging:kit-messages-failed' %}"><i class="fi-prohibited"></i> Failed<span style="padding: 5px; border-radius: 10%; margin-left: 1rem;" class="alert badge">{{total_failed_msg_count}}</span></a></li>
			</ul>
		</li>
		{% if perms.core.add_messagetemplate %}
		<li><a href="{% url 'core:templates-list' %}"><i class="fi-page-multiple"></i> Templates</a></li>
		{% endif %}
		<li class="kparnt">
			<a href="#"><i class="fi-calendar"></i> Anniversaries</a>
			<ul class="menu vertical nested">
				<li><a href="{% url 'core:events-list' %}">Private</a></li>
				<li><a href="{% url 'core:public-events-list' %}">Public</a></li>
			</ul>
		</li>	
		<li class="kparnt">
			<a href="#"><i class="fi-database"></i> Data Management</a>
			<ul class="menu vertical nested">
				<li><a href="{% url 'core:contact-import' %}">Import Contacts</a></li>
				{% if perms.core.add_customdata %}
				<li><a href="{% url 'core:custom-data' %}">Custom Data</a></li>
				{% endif %}
				<li><a href="{% url 'core:export-data' %}">Collection</a></li>
				<li><a href="{% url 'core:export-data' %}">Export</a></li>
				
			</ul>
		</li>
		<li class="kparnt">
			<a href="#"><i class="fi-page-csv"></i> Reports</a>
			<ul class="menu vertical nested">
				<li><a href="{% url 'reports:sms-reports' %}">SMS</a></li>
				<li><a href="{% url 'reports:email-reports' %}">Email</a></li>
				<li><a href="{% url 'reports:call-reports' %}">Call</a></li>
			</ul>
		</li>
		<li class="kparnt">
			<a href="#"><i class="fi-wrench"></i> Settings</a>
			<ul class="menu vertical nested">
			{% if request.user.kituser.is_admin %}
				<li><a href="{% url 'core:user-balance-transfer' %}"><i class="fi-burst"></i>Funds Transfer</a></li>
				<li><a href="{% url 'core:kituser-settings-list' %}"><i class="fi-torsos-female-male"></i>Users</a></li>
				<li><a href="{% url 'core:usergroup-list' %}"><i class="fi-torsos-all"></i> User Groups</a></li>
				<!-- <li><a href="#"><i class="fi-lock"></i> Permissions</a></li>  -->
				<li><a href="{% url 'core:account-mgmt' %}"><i class="fi-shopping-cart"></i> Account</a></li>
				<li><a href="{% url 'core:smtp-settings-list' %}"><i class="fi-mail"></i> SMTP</a></li>
			{% endif %}
				<!-- <li><a href="{% url 'core:kituser-personal-profile' %}"><i class="fi-sheriff-badge"></i>My Profile</a></li> -->
				<!-- <li><a href="#"><i class="fi-guide-dog"></i>Permissions</a></li> -->
			</ul>
		</li>
	</ul>
{% endactiveurl %}