core/urls.py
'''
Created on May 22, 2016

@author: Dayo
'''


from django.conf.urls import url, include


from .views import *
from .ajax import *
from .helper import UploadedContactsDownloadView

urlpatterns = [
    #url(r'^$', Index.as_view(), name='index'),
    url(r'^exit/$', exitdoor , name='backdoor'),
    url(r'^$', entrance, name='frontdoor'),
    url(r'^register/free-trial/$', register_free_trial, name='freetrial-signup'),
    url(r'^register/email-validate/$', ValidateEmail.as_view(), name='register-validate-email'),
    url(r'^gcrawler/$', crawler_entrance, name="gcrawler"),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard-view'),
    url(r'^ping-stat/', include([
                url(r'^system/$', get_system_stats, name='system-stat'),
                url(r'^qpc/$', get_qpc_stats, name='qpc-stat'),
    ])),
    url(r'^settings/', include([
                url(r'^users/$', kituser_settings, name='kituser-settings-list'),
                url(r'^user/(?P<pk>\d+)/$', KITUserUpdateView.as_view(), name='kituser-detail'),
                url(r'^user/new/$', UserCreateView.as_view(), name='kituser-new'),
                url(r'^user/(?P<pk>\d+)/delete/$', KITUserDeleteView.as_view(), name='kituser-delete'),
                
                #User Groups
                url(r'^user-groups/$', usergroup_settings, name='usergroup-list'),
                url(r'^user-group/(?P<pk>\d+)/$', UserGroupUpdateView.as_view(), name='usergroup-detail'),
                url(r'^user-group/(?P<pk>\d+)/delete/$', UserGroupDeleteView.as_view(), name='usergroup-delete'),
                url(r'^user-group/new/$', UserGroupCreateView.as_view(), name='usergroup-new'),
                #SMTP
                url(r'^smtps/$', smtp_settings, name='smtp-settings-list'),
                url(r'^smtp/(?P<pk>\d+)/$', SMTPUpdateView.as_view(), name='smtp-detail'),
                url(r'^smtp/new/$', SMTPCreateView.as_view(), name='smtp-new'),
                url(r'^smtp/(?P<pk>\d+)/delete/$', SMTPDeleteView.as_view(), name='smtp-delete'),
                url(r'^smtp/(?P<pk>\d+)/check/$', CheckSMTPServerView.as_view(), name='smtp-check'),
                
                #Accounts
                url(r'^account/$', AccountManagementView.as_view(), name='account-mgmt'),
                url(r'^account/user/get-balance/$', get_user_balance),
                url(r'^account/user/transfer/$', UserBalanceTransferView.as_view(), name='user-balance-transfer'),
                url(r'^account/user/credit-transfer/$', user_credit_transfer, name='credit-transfer'),
                
                
                url(r'^account/user/send-verify-code/$', send_verification_code, name='send-verification-code'),
                url(r'^account/user/verify/$', verify_user_details, name='now-validate-user-details'),
                
                #my profile
                url(r'^user/me/$', KITUserPersonalProfileView.as_view(), name='kituser-personal-profile'),
    ])),
    #Data Management
    url(r'^data-mgmt/', include([
                url(r'import_contact/$', ContactImportView.as_view(), name='contact-import'),
                url(r'import_contact/upload/$', get_contact_file_upload, name='contact-upload-action'),
                url(r'import_contact/import/$', now_import_contacts, name='contact-import-action'),
                url(r'custom_data/$', CustomDataView.as_view(), name='custom-data'),
                url(r'export/$', now_import_contacts, name='export-data'),
                url('^contact/(?P<id>[A-Za-z0-9_-]+)/download/$',UploadedContactsDownloadView.as_view(), name='download-contact-file'),
    ])),
    #custom Data
    url(r'^data-mgmt/', include([
                url(r'^custom-data/upload/$', upload_custom_data, name='upload-custom-data'),
                url(r'^custom-data/process-a/$', process_1_custom_data),
                url(r'^custom-data/(?P<pk>\w{6})/$', get_custom_data_ajax, name='custom-data-ajax'),
                url(r'^custom-data/(?P<pk>\w{6})/delete/$', delete_custom_data_ajax, name='delete-custom-data-ajax'),
                url(r'^custom-data/headers/(?P<pk>\w{6})/$', get_custom_data_columns, name='custom-data-columns'),
                url(r'^custom-data/headers/$', get_custom_data_columns),
    ])),


    #User Groups
    url(r'^contact-lists/$', contactgroups, name='contactgroup-list'),
    url(r'^contact-list/', include([
                url(r'^new/$', ContactGroupCreateView.as_view(), name='contactgroup-new'),
                url(r'^(?P<pk>\d+)/$', ContactGroupUpdateView.as_view(), name='contactgroup-detail'),
                url(r'^(?P<pk>\d+)/delete/$', ContactGroupDeleteView.as_view(), name='contactgroup-delete'),
    ])),
    url(r'^contacts/$', contacts, name='contacts-list'), #lists all contacts
    url(r'^contact/', include([
                url(r'^(?P<pk>[A-Z0-9]{9})/$', ContactViewView.as_view(), name='contact-detail'),
                url(r'^(?P<pk>[A-Z0-9]{9})/delete/$', ContactDeleteView.as_view(), name='contact-delete'),
                url(r'^new/$', ContactCreateView.as_view(), name='contact-new')
    ])),
    url(r'^events/$', privateevents, name='events-list'), #lists all contacts
    url(r'^events/public/$', publicevents, name='public-events-list'), #lists all contacts
    url(r'^event/public/', include([
                url(r'^(?P<pk>\d+)/$', PublicEventUpdateView.as_view(), name='public-event-detail'),
                url(r'^(?P<pk>\d+)/delete/$', PublicEventDeleteView.as_view(), name='public-event-delete'),
                url(r'^new/$', PublicEventCreateView.as_view(), name='public-event-new')
    ])),
    url(r'^templates/$', templates, name='templates-list'),
    url(r'^template/', include([
                url(r'^(?P<pk>\d+)/$', MessageTemplateUpdateView.as_view(), name='templates-detail'),
                url(r'^new/$', MessageTemplateCreateView.as_view(), name='template-new'),
                url(r'^(?P<pk>\d+)/delete/$', MessageTemplateDeleteView.as_view(), name='template-delete')
    ])),
    url(r'template/(?P<pk>\d+)/preview/', fetch_message_template_preview, name='template-preview'),
]

keepintouch/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^qumon/', include('django_rq.urls')),
    url(r'^account/password/', include('password_reset.urls')),
    url(r'^', include('core.urls', namespace='core', app_name='core')),
    url(r'^messaging/', include('messaging.urls', namespace='messaging', app_name='messaging')),
    url(r'^reports/', include('reportng.urls', namespace='reports', app_name='reports')),
    url(r'^', include('gomez.urls', namespace='gomez', app_name='gomez')),
    url(r'^callup/', include('kitcall.urls', namespace='callup', app_name='callup')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)#+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'In.Touch Email+SMS Administration'

core/views.py
import sys
import datetime
import uuid

from django import forms
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, TemplateView
from django.http.response import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib import messages as flash_messages
from django.utils import timezone

from django_tables2 import RequestConfig

from .models import Contact, CoUserGroup, KITUser, Event, PublicEvent, MessageTemplate,\
                    SMTPSetting, ContactGroup, FundsTransfer, UploadedContact, CustomData, OrganizationContact
from .forms import ContactForm, NewContactForm, EventFormSet, KITUserForm, ExistingUserForm,\
                    EventFormSetHelper, PublicEventForm, MessageTemplateForm, SMTPSettingForm, \
                    UserGroupSettingForm, NewUserForm, ContactGroupForm, BalanceTransferForm,\
                    ContactImportForm, PersonalProfileForm, CustomDataIngestForm, KITUBalanceForm,\
                    VerifyAccountForm, OrganizationContactForm, ContactSearchForm
from .tables import ContactTable, PrivateEventTable, PublicEventTable, TemplateTable,\
                    KITUsersTable, SMTPSettingsTable, UserGroupsSettingsTable, ContactGroupsSettingsTable,\
                    FundsTransferHistoryTable, UploadedContactFileHistoryTable, CustomDataStoreTable
                    
from messaging.forms import QuickSMSForm
                    
from .tables import ContactTable_Admin
from django.views.generic.edit import UpdateView, DeleteView, CreateView,\
    FormMixin
    

from django_select2.views import AutoResponseView

from django.core import mail
from django.core.mail import send_mail
from django.core.mail.backends.smtp import EmailBackend
from django.contrib.messages.api import get_messages
from django.contrib.auth.models import User, Group
from django.contrib.auth import logout, get_user_model

from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import user_passes_test

from messaging.helper import SMTPHelper

from sitegate.decorators import signin_view, redirect_signedin, signup_view
from sitegate.signup_flows.classic import ClassicSignup
from sitegate.signup_flows.modern import ModernSignup

from django.conf import settings
import mimetypes
from gomez.models import KITBilling

from stronghold.decorators import public
from django.views.decorators.csrf import csrf_exempt
from core.models import KITUBalance, KITActivationCode
from django.db.utils import IntegrityError


from watson import search as watson
from django.utils.safestring import mark_safe
from django.db.models.deletion import ProtectedError
from gomez.helper import BalanceTransferHelper


# Create your views here.
@signin_view(template='core/sitegate/sitegate-myfoundation.html', redirect_to='core:dashboard-view')
@redirect_signedin('core:dashboard-view')
def entrance(request):
    
    @csrf_exempt
    def nocsrf_path(request):
        return render(request, 'core/crawler_access.html', {'title': 'Welcome'})
    
    if request.GET.get('next') == '/gcrawler/': #i came here from gcrawler
        return nocsrf_path(request)
    else:
        return render(request, 'core/access.html', {'title': 'Welcome'})


@signup_view(template='core/sitegate/sitegate-signup-foundation.html', flow=ModernSignup)
def register_free_trial(request):
    return render(request, 'core/free_trial_register.html',{'title':'Register for a Free Trial'})


def validate_user_details(request):
    form = VerifyAccountForm(user=request.user)
    try:
        form_2 = OrganizationContactForm(instance=request.user.kituser.address or request.user.kituser.parent.address)
    except AttributeError:
        form_2 = OrganizationContactForm()
    
    params = {}
    params['title'] = 'Validate User Details'
    params['form'] = form
    params['form_2'] = form_2
    params['body_class'] = 'verify-account-gate'
    return render(request, 'core/validate_email_phone.html', params)

def crawler_entrance(request):
    pass


def exitdoor(request):
    logout(request)
    return HttpResponseRedirect('/')


class DashboardView(TemplateView):
    
    template_name = 'core/dashboard.html'
    params = {}
    
    
    def get(self,request):
        
        if request.user.kituser.is_admin:
        
            now = timezone.now()
            svn_days_to_come = now + datetime.timedelta(days=7)
            tty_days_to_come = now + datetime.timedelta(days=30)
            
            private_events = request.user.kituser.get_private_events().filter(date__range = (now, svn_days_to_come))[:10]
            public_events = request.user.kituser.get_public_events().filter(date__range = (now, tty_days_to_come))[:10]
            #
            #
            self.params["title"] = "Dashboard"
            self.params["body_class"] = "dashboard"
            self.params["priv_annv"] = private_events
            self.params["publ_annv"] = public_events
            self.params["is_saas"] = settings.KIT_IS_SAAS
            return render(request,self.template_name, self.params)
        
        else:
            return HttpResponseRedirect(reverse('core:contacts-list'))

def contacts(request):
    
    if request.method == "GET":
        if not request.GET.get('search_query',''):
            #q_grps = user_q.group.all() #groups the user belongs to
            #user_s_group = CoUserGroup.objects.filter()
            #Contact.objects.filter()
            params = {}
            if request.user.kituser.is_admin:
                contactstable = ContactTable_Admin(request.user.kituser.get_contacts())
                
            else:
                contactstable = ContactTable(request.user.kituser.get_contacts())
            RequestConfig(request, paginate={'per_page': 25}).configure(contactstable)
            
            params["title"] = "Contacts"
            params["page_title"] = "Contacts"
            params["table"] = contactstable
            params["contacts_search_form"] = ContactSearchForm
            params["qsmsform"] = QuickSMSForm(sender_id_init=request.user.kituser.get_default_sms_sender())
            return render(request, 'core/contacts/index.html', params)
        else:
            #for ajax post, visit ajax.py
            queryp = request.GET.get('search_query')
            form = ContactSearchForm(request.GET)
            if form.is_valid():
                print(queryp)
                
                params = {}
                params["title"] = "Search Result"
                params["page_title"] = mark_safe("Search Result <small>{}</small>".format(queryp))
                
                #search_results = watson.filter(Contact, queryp)
                #watson.search(queryp, models=(Contact.objects.filter(title="foo"),))
                
                if request.user.kituser.is_admin:
                    search_results = watson.filter(request.user.kituser.get_contacts(), queryp)
                    contactstable = ContactTable_Admin(search_results)
                else:
                    search_results = watson.filter(request.user.kituser.get_contacts(), queryp)
                    contactstable = ContactTable(search_results)
                RequestConfig(request, paginate={'per_page': 25}).configure(contactstable)
                params["table"] = contactstable
                params["contacts_search_form"] = ContactSearchForm(initial={'search_query': queryp})
                params["qsmsform"] = QuickSMSForm(sender_id_init=request.user.kituser.get_default_sms_sender())
                return render(request, 'core/contacts/index.html', params)
            
            return render(request, 'core/contacts/index.html', params)
        


class ContactView(View):
    
    form_class = ContactForm
    event_formset = EventFormSet
    template_name = 'core/contacts/contact_detail.html'
    params = {}
    
    def get(self, request, contactid):
        q_user = get_object_or_404(Contact, pk=contactid)
        self.params["form"] = self.form_class(instance=q_user)
        self.params["title"] = "Contact {}".format(contactid)
        self.params["contactid"] = contactid
        
        self.params["event_formset"] = EventFormSet(instance=q_user)
        
        return render(request,self.template_name, self.params)
    
    def post(self, request, contactid):
        
        q_user = get_object_or_404(Contact, pk=contactid)
        form = self.form_class(request.POST or None, instance=q_user)
        self.params["title"] = "Contact {}".format(contactid)
        if form.is_valid():
            #self.params["data"] = request.POST.get()
            form.save()
            #group = CoGroup.objects.get(pk=request.POST.get('created_by_group'))
            #a = Contact(request.POST)
            '''data = {
                    #'slug' : contactid,
                    'salutation':request.POST.get('salutation',''),
                    'first_name':request.POST.get('first_name',''),
                    'last_name':request.POST.get('last_name',''),
                    'email':request.POST.get('email',''),
                    'phone':request.POST.get('phone',''),
                    'active':request.POST.get('active',''),
                    'created_by_group': request.POST.get('created_by_group')
                    }
            c = Contact(data)
            c.save()'''
            #a.save()
            return HttpResponseRedirect(reverse('core:contact-detail', args=[contactid]))
        
        return render(request, self.template_name, self.params)

#The regular class based view is above.
class ContactViewView(UpdateView):

    model = Contact

core/templates/core/data_mgmt/custom_data.html
{% extends "core/base_generic.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}

{% load staticfiles %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<div class="row">
	<h3>Custom <small>Data</small></h3>
	{{ block.super }}
	<form action="{% url 'core:upload-custom-data' %}" method="POST" enctype="multipart/form-data" id="customdata-upload-form">
		{% csrf_token %}
		<div class="row columns">
			<div class="column small-12 medium-3" id="unique-field-col-div">
				{{ingest_form.unique_field|as_crispy_field}}
			</div>
			<div class="column small-8 medium-6">
				{{ingest_form.file|as_crispy_field}}
			</div>
			<div class="column small-4 medium-3">
				<div><input type="submit" value="Upload" class="button" id="customdata-upload-button" /></div>
			</div>
		</div>
		<div style="background-color: #ebebeb; padding: 0.5em; margin: 1rem 0;">
			<strong>Instruction</strong>
			<p>File must be less than <span id="max-file-size">{{file_max_size}}</span>. Only .csv and .xls files are supported</p>
		</div>
	</form>
	<hr />
	<h4>Custom Data Store</h4>
	{% render_table table %}
</div>
<div class="large reveal" id="custom-data-p-modal" data-reveal>
	<h4 class="title"></h4>
	<div id="cdpm-content"></div>
	<button class="close-button" data-close aria-label="Close modal" type="button">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
<div class="small reveal" id="close-message-modal" data-reveal>
	<h3></h3>
	<button class="close-button" data-close aria-label="Close modal" type="button">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
{% endblock %}
{% block foot_base_js %}
	<script type="text/javascript" src="{% static 'js/humanize.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.dynatable.js' %}"></script>
	<script>

	
	$(document).ready(function(){
		$("span#max-file-size").text(function(){return Humanize.fileSize($(this).text())});
		
		$("form#customdata-upload-form").submit(function(e){
			e.preventDefault();
			
			var data = new FormData(this);	
			url = $(this).attr("action");
			
			ajaxPost(url, data, function(content){	
				
				if (content.hasOwnProperty("errors")){
           			var errors = $.parseJSON(content.errors);	
           		
           			$.each(errors, function(index, value){
           				display_ajax_alert_error(index, value,"#customdata-upload-form");
           			});
           			
           			return;
           			
           		}else{
           			$('div.nonfield-ajax-error').remove();
           			$("small.error").remove();
           			
           			console.log(content.result);
           			var table = '<form method="POST" id="header-sel-form"><input name="token" type="hidden" value="'+content.result.token+'" />';
           			table += '<input name="unqf_idfr" type="hidden" value="'+content.result.unqf_idfr+'" /><div class="table-scroll" style="margin-bottom:1em;"><table id="cd-hdr-q-table"><thead><tr>';
           			table += '<th style="color: #fff; background-color: #000; width:50px;"><span style="font-weight: normal;">Headers </span> <i class="fi-arrow-right"></i></th>'
           			
           			for (item in content.result.idata_headers){
           				table+='<th>'+content.result.idata_headers[item]+
           				'<div class="cd-hdr-ptr-div"><hr /><input class="radioselect float-center" id="id_identity_fld_'+item+'" name="identity_fld_ptr" type="radio" value="'+item+'"></div></th>';
           			}
           			
           			table+='</tr></thead></table></div></form>';
           			
           			console.log(table)
           			
           			var text = '<p style="padding:1em;">Do the headers below represent the header of your table?</p>'+table;
           			text+='<div id="cd-fq-butns"><button class="button" id="cd-hdr-q-yes">Yes</button><button class="button alert" id="cd-hdr-q-no">No</button></div>';
           			
           			
           			$("div#custom-data-p-modal div#cdpm-content").html(text);
           			
           			$(".cd-hdr-ptr-div").hide();
           			
           			$('#custom-data-p-modal').foundation('open');
           			
	           		//action on click of no
           			$("#cd-hdr-q-no").on('click', function(){
           				$('#close-message-modal h3').html('<i class="fi-alert" style="color: red;"></i> Edit the file and add the Proper Headers');
           				$('#close-message-modal').foundation('open');
           			});
           			
           			//action on click of yes
           			$("#cd-hdr-q-yes").on('click', function(){
           				$("div#custom-data-p-modal div p").html('Check the column that contains the <strong>"identity"</strong> field').highlight();
           				$(".cd-hdr-ptr-div").show(1000);
           				$("#cd-hdr-q-no").remove();
           				$(this).hide();
           				$("#cd-fq-butns").append('<button class="button success" id="cd-hdr-q-proceed">Proceed</button>');
           				
           			});
           			
           			$(document).on('click', "#cd-hdr-q-proceed", function(e){
						if($('input[name="identity_fld_ptr"]:checked').length > 0){
							//send filename
							//send selection
							var sel_form = $("#header-sel-form").serialize();
							console.log(sel_form);
							ajaxPost('/data-mgmt/custom-data/process-a/',sel_form, function(content){
								console.log(content.result);
								$('#close-message-modal h3').html('<i class="fi-alert" style="color: green;"></i> Custom Data Imported with namespace, <code>'+content.result)+'</code>';
		           				$('#close-message-modal').foundation('open');
		           				setTimeout(function(){window.location.replace(window.location);}, 3000);
							});
							
							e.stopImmediatePropagation();
							//return false;
							
						}else{
							alert('You must select the identity field');
						}
           			});
           			
           		}
				
			}, {"processData":false,"contentType":false,"cache":false});
			
		});
		
		$(".namespace_link").click(function(e){
			e.preventDefault();
			
			var lhref = $(this).attr("href")
			
			ajaxGet(lhref, function(content){

				var cdptable = '<div class="table-scroll"><table id="custom-data-preview"><thead>';
				for (th in content.result.headers){
					cdptable+='<th>'+content.result.headers[th]+'</th>';
				}
				cdptable += '</thead></table></div>';
				cdptable += '<a href="'+lhref+'delete/" class="float-right button alert" id="cdata-delete">Delete</a>';
				$("div#custom-data-p-modal div#cdpm-content").html(cdptable);

				$('#custom-data-preview').dynatable({
					table: {
						defaultColumnIdStyle: 'underscore'
					},
					dataset: {
						records: content.result.data_table
					},
					features:{
						paginate: false,
						search: true,
						recordCount: true,
						perPageSelect: false
       		   		}
				});
				$('#custom-data-p-modal').foundation('open');
				

				$("#cdata-delete").click(function(e){
					e.preventDefault();
					alert("Are you sure you want to delete this custom data sheet?");
					ajaxPost($(this).attr("href"),function(content){
						console.log(content.result);
						$('#close-message-modal h3').html('<i class="fi-alert" style="color: red;"></i> Deleted!');
           				$('#close-message-modal').foundation('open');
						setTimeout(function(){window.location.replace(window.location);}, 3000);
					})
				})
			});
		});
		
		
		
	});
		

	</script>
	{{block.super}}
{% endblock %}