core/urls.py
'''
Created on May 22, 2016

@author: Dayo
'''


from django.conf.urls import url, include


from .views import *
from .ajax import *
from .helper import UploadedContactsDownloadView

urlpatterns = [
    #url(r'^$', Index.as_view(), name='index'),
    url(r'^exit/$', exitdoor , name='backdoor'),
    url(r'^$', entrance, name='frontdoor'),
    url(r'^register/free-trial/$', register_free_trial, name='freetrial-signup'),
    url(r'^register/email-validate/$', ValidateEmail.as_view(), name='register-validate-email'),
    url(r'^gcrawler/$', crawler_entrance, name="gcrawler"),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard-view'),
    url(r'^ping-stat/', include([
                url(r'^system/$', get_system_stats, name='system-stat'),
                url(r'^qpc/$', get_qpc_stats, name='qpc-stat'),
    ])),
    url(r'^settings/', include([
                url(r'^users/$', kituser_settings, name='kituser-settings-list'),
                url(r'^user/(?P<pk>\d+)/$', KITUserUpdateView.as_view(), name='kituser-detail'),
                url(r'^user/new/$', UserCreateView.as_view(), name='kituser-new'),
                url(r'^user/(?P<pk>\d+)/delete/$', KITUserDeleteView.as_view(), name='kituser-delete'),
                
                #User Groups
                url(r'^user-groups/$', usergroup_settings, name='usergroup-list'),
                url(r'^user-group/(?P<pk>\d+)/$', UserGroupUpdateView.as_view(), name='usergroup-detail'),
                url(r'^user-group/(?P<pk>\d+)/delete/$', UserGroupDeleteView.as_view(), name='usergroup-delete'),
                url(r'^user-group/new/$', UserGroupCreateView.as_view(), name='usergroup-new'),
                #SMTP
                url(r'^smtps/$', smtp_settings, name='smtp-settings-list'),
                url(r'^smtp/(?P<pk>\d+)/$', SMTPUpdateView.as_view(), name='smtp-detail'),
                url(r'^smtp/new/$', SMTPCreateView.as_view(), name='smtp-new'),
                url(r'^smtp/(?P<pk>\d+)/delete/$', SMTPDeleteView.as_view(), name='smtp-delete'),
                url(r'^smtp/(?P<pk>\d+)/check/$', CheckSMTPServerView.as_view(), name='smtp-check'),
                
                #Accounts
                url(r'^account/$', AccountManagementView.as_view(), name='account-mgmt'),
                url(r'^account/user/get-balance/$', get_user_balance),
                url(r'^account/user/transfer/$', UserBalanceTransferView.as_view(), name='user-balance-transfer'),
                url(r'^account/user/credit-transfer/$', user_credit_transfer, name='credit-transfer'),
                
                
                url(r'^account/user/send-verify-code/$', send_verification_code, name='send-verification-code'),
                url(r'^account/user/verify/$', verify_user_details, name='now-validate-user-details'),
                
                #my profile
                url(r'^user/me/$', KITUserPersonalProfileView.as_view(), name='kituser-personal-profile'),
    ])),
    #Data Management
    url(r'^data-mgmt/', include([
                url(r'import_contact/$', ContactImportView.as_view(), name='contact-import'),
                url(r'import_contact/upload/$', get_contact_file_upload, name='contact-upload-action'),
                url(r'import_contact/import/$', now_import_contacts, name='contact-import-action'),
                url(r'custom_data/$', CustomDataView.as_view(), name='custom-data'),
                url(r'export/$', now_import_contacts, name='export-data'),
                url('^contact/(?P<id>[A-Za-z0-9_-]+)/download/$',UploadedContactsDownloadView.as_view(), name='download-contact-file'),
    ])),
    #custom Data
    url(r'^data-mgmt/', include([
                url(r'^custom-data/upload/$', upload_custom_data, name='upload-custom-data'),
                url(r'^custom-data/process-a/$', process_1_custom_data),
                url(r'^custom-data/(?P<pk>\w{6})/$', get_custom_data_ajax, name='custom-data-ajax'),
                url(r'^custom-data/(?P<pk>\w{6})/delete/$', delete_custom_data_ajax, name='delete-custom-data-ajax'),
                url(r'^custom-data/headers/(?P<pk>\w{6})/$', get_custom_data_columns, name='custom-data-columns'),
                url(r'^custom-data/headers/$', get_custom_data_columns),
    ])),


    #User Groups
    url(r'^contact-lists/$', contactgroups, name='contactgroup-list'),
    url(r'^contact-list/', include([
                url(r'^new/$', ContactGroupCreateView.as_view(), name='contactgroup-new'),
                url(r'^(?P<pk>\d+)/$', ContactGroupUpdateView.as_view(), name='contactgroup-detail'),
                url(r'^(?P<pk>\d+)/delete/$', ContactGroupDeleteView.as_view(), name='contactgroup-delete'),
    ])),
    url(r'^contacts/$', contacts, name='contacts-list'), #lists all contacts
    url(r'^contact/', include([
                url(r'^(?P<pk>[A-Z0-9]{9})/$', ContactViewView.as_view(), name='contact-detail'),
                url(r'^(?P<pk>[A-Z0-9]{9})/delete/$', ContactDeleteView.as_view(), name='contact-delete'),
                url(r'^new/$', ContactCreateView.as_view(), name='contact-new')
    ])),
    url(r'^events/$', privateevents, name='events-list'), #lists all contacts
    url(r'^events/public/$', publicevents, name='public-events-list'), #lists all contacts
    url(r'^event/public/', include([
                url(r'^(?P<pk>\d+)/$', PublicEventUpdateView.as_view(), name='public-event-detail'),
                url(r'^(?P<pk>\d+)/delete/$', PublicEventDeleteView.as_view(), name='public-event-delete'),
                url(r'^new/$', PublicEventCreateView.as_view(), name='public-event-new')
    ])),
    url(r'^templates/$', templates, name='templates-list'),
    url(r'^template/', include([
                url(r'^(?P<pk>\d+)/$', MessageTemplateUpdateView.as_view(), name='templates-detail'),
                url(r'^new/$', MessageTemplateCreateView.as_view(), name='template-new'),
                url(r'^(?P<pk>\d+)/delete/$', MessageTemplateDeleteView.as_view(), name='template-delete')
    ])),
    url(r'template/(?P<pk>\d+)/preview/', fetch_message_template_preview, name='template-preview'),
]

gomez/urls.py
'''
Created on Jul 13, 2016

@author: Dayo
'''

from django.conf.urls import url, include

from .views import *

urlpatterns = [
    url(r'^settings/', include([
        url(r'^my/system/$', SystemSettingsUpdateView.as_view(), name='system-settings'),
        url(r'^account/expired/$', SubscriptionExpired.as_view(), name='account-expired'),
                
                
    ])),
               
    url(r'^order/', include([
            url(r'^start/$', OrderStart.as_view(), name='order-start'),
            url(r'^(?P<order_id>[A-Z0-9]{10})/$', OrderCart.as_view(), name='order-cart'),
            url(r'^(?P<order_id>[A-Z0-9]{10})/update/$', UpdateCart.as_view(), name='order-update'),
            url(r'^(?P<order_id>[A-Z0-9]{10})/item/(?P<id>\d+)/delete/$', DeleteCartItem.as_view(), name='order-delete-item'),
            url(r'^checkout/$', OrderCheckout.as_view(), name='order-checkout'),
            #url(r'^paynow/$', get_qpc_stats, name='order-checkout'),
    ])),
]

keepintouch/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^qumon/', include('django_rq.urls')),
    url(r'^account/password/', include('password_reset.urls')),
    url(r'^', include('core.urls', namespace='core', app_name='core')),
    url(r'^messaging/', include('messaging.urls', namespace='messaging', app_name='messaging')),
    url(r'^reports/', include('reportng.urls', namespace='reports', app_name='reports')),
    url(r'^', include('gomez.urls', namespace='gomez', app_name='gomez')),
    url(r'^callup/', include('kitcall.urls', namespace='callup', app_name='callup')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)#+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'In.Touch Email+SMS Administration'

gomez/forms.py
'''
Created on Jul 26, 2016

@author: Dayo
'''
from django import forms
from django.utils.translation import ugettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML
from crispy_forms_foundation.layout import ButtonGroup, ButtonHolder, Div,\
                                            Submit, Reset, Button, Layout, Fieldset, Row, Column
                                            
from .models import KITSystem

class SystemSettingsForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(SystemSettingsForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_action = '.'
        self.helper.form_tag = True
        self.helper.add_input(Submit('submit', _('Update'), css_class="success float-right"))
        self.helper.add_input(Reset('reset', _('Reset'), css_class="float-right"))
        self.fields['did_number'].disabled = True
    
    class Meta:
        model = KITSystem
        fields = ['company_wide_contacts', 'default_sms_sender','sms_unsubscribe_message','did_number',\
                  'max_standard_message','default_message_send_time']
        widgets = {
            'sms_unsubscribe_message' : forms.Textarea(attrs={'rows':5, 'cols': 30}),
            'default_message_send_time' : forms.TimeInput(format=('%H:%M'), attrs={'type':'time'})
                   }


    

gomez/views.py
from django.views.generic import UpdateView, View

from .models import KITSystem, Product, KITBilling, Order, OrderLine
from .forms import SystemSettingsForm

from django.shortcuts import render, get_object_or_404
from ipware.ip import get_real_ip

import prices
import logging
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.conf import settings

logger = logging.getLogger(__name__)
    
class SystemSettingsUpdateView(UpdateView):
    
    model = KITSystem
    form_class = SystemSettingsForm
    template_name = 'gomez/system_settings.html'
    
    def get_object(self, queryset=None):
        return self.request.user.kituser.kitsystem
    
    def get_context_data(self, **kwargs):
        params = super(SystemSettingsUpdateView, self).get_context_data(**kwargs)
        params["syssetid"] = self.object.pk
        return params
    
    def get_queryset(self):
        # user should not be able to view the settings of other users
        qs = super(SystemSettingsUpdateView, self).get_queryset()
        return qs.filter(kit_admin=self.request.user.kituser)


class SubscriptionExpired(View):
    
    template = 'gomez/order/subscription_expired_landing_page.html'
    params = {}
    
    def get(self, request):
        subsc_plans = Product.objects.filter(meta__type='subscription', meta__sub_type='plan', active=True).order_by('price').values()
        user_plan = KITBilling.objects.get(kit_admin = request.user.kituser).service_plan
        # if order exists, then renew...and provide other options in case user wants to upgrade or downgrade
        # else provide all the options
        self.params["subscription_products"] = subsc_plans
        
        return render(request, self.template, self.params)

class OrderStart(View):
    
    
    params = {}
    
    def get(self, request):
        product_id = request.GET.get('product_id')
        if request.GET.get('action') == 'renew':
            # return the cart with the ministore
            # get the existing subscription order
            try:
                current_order = request.user.kituser.order
                
            except AttributeError:
                # no order exists
                pass #log this
            
        elif request.GET.get('action') == 'resub':
            # get product to subscribe for
            subsc_product = Product.objects.get(pk=product_id)

            # create order
            corder = Order.objects.create(
                    ip_address = get_real_ip(request),
                    customer = request.user.kituser,
                    billing_address = request.user.kituser.address,
                                          )            
            # create orderline
            porderl = OrderLine.objects.create(
                    product = subsc_product,
                    unit_price_net = subsc_product.price.net,
                    unit_price_gross = subsc_product.price.gross,
                    billing_cycle = OrderLine.ANNUALLY,
                    quantity = 1,
                    order = corder
                    )
            corder.total = porderl.product.price
            corder.save()
            return HttpResponseRedirect(reverse('gomez:order-cart', kwargs={'order_id':corder.order_number}))  


class OrderCart(View):
    
    params = {}
    template = 'gomez/order/order_start.html'
    
    def get(self, request, order_id):
        
        corder = get_object_or_404(Order, order_number=order_id)
        
        self.params['mini_store'] = Product.objects.exclude(meta__type="subscription").exclude(active=False).\
                                    values('name','description','meta','price')
        
        self.params['corder'] = corder
        self.params['title'] = "Order {}".format(corder.order_number)
    
        self.params['corder_p_items'] = corder.get_items().values()
        
        return render(request, self.template, self.params)
    
class UpdateCart(View):

    
    def post(self, request, order_id):
        print(request.POST)
        for itemline in request.POST:
            if itemline.isnumeric():
                OrderLine.objects.get(pk=itemline).change_quantity(request.POST.get(itemline))
        # update order summary
        order = Order.objects.get(order_number=order_id)
        total = sum([item.get_line_total() for item in order], prices.Price(0, currency=settings.DEFAULT_CURRENCY))
        order.total = total
        order.save()
        
        return HttpResponseRedirect(reverse('gomez:order-cart', args=[order_id]))



class DeleteCartItem(View):
    
    pass

class OrderCheckout(View):
    pass

gomez/templates/gomez/order/order_start.html
{% extends "core/base_generic.html" %}

{% load staticfiles %}
{% load gmz_extras %}
{% load prices_i18n %}

{% block head_base_links %}
	{{ block.super }}
{% endblock %}
{% block title %}{{title}}{% endblock %}

{% block container %}
	<div class="small-12 large-12 column kitapp-content">
		{% block content %}
			{% if messages %}
			<div class="alert callout">
				{% for message in messages %}
					<p>{{ message }}</p>
				{% endfor %}
			</div>
			{% endif %}
			<div class="row">
				<h3>Order # <span style="color: #444; font-size: 75%;">{{corder.order_number}}</span></h3>
				<div class="column small-12 medium-9">
					<form action="{% url 'gomez:order-update' corder.order_number %}" method="post">
						{% csrf_token %}
						<div class="shop-order">
							<table>
								<tr>
									<th width="40%"></th>
									<th>Price</th>
									<th>Quantity</th>
									<th></th>
								</tr>
								{% for item in corder %}
									<tr>
										<td>
											<strong>{{item.product.name}}</strong>
											<p style="color: #555; font-size: 70%">{{item.product.description}}</p>
										</td>
										<td style="text-align: center;">{% gross item.get_price_per_item %}</td>
										<td class="cart-item-row" style="text-align: center;">
											<input name="{{item.id}}" type="number" value="{{item.get_quantity}}" style="width: 4rem; display: inline-block;" min="1" />
											<span class="cart-item-update"><a href="#">update</a></span>
										</td>
										<td>
											<a href="#"><i style="color: red" class="fi-x" title="Remove Item"></i></a>
										</td>
									</tr>
								{% endfor %}
							</table>
						</div>
					</form>
					<div class="shop-mini-store">
						<h3>Store <small>Other Items that go with your selection</small></h3>
					</div>
				</div>
				<div class="column small-12 medium-3 order-summary">
					<h4>Order Summary</h4>
					<p>
						{{corder.get_items.count}} item{{corder.get_items.count|pluralize}} in your order.
					</p>
					<hr />
					<h4 style="font-weight: bold; color: orangered; text-align: center;">{% gross corder.total %}</h4>
					<button style="color: black; width: 10rem; display: block; margin: 1rem auto;" class="button warning">Checkout</button>
				</div>
			</div>
		{% endblock %}
	</div>

{% endblock %}

{% block foot_base_js %}
	{{ block.super }}
	<script type="text/javascript" src="{% static "js/humanize.js" %}"></script>
	<script>
		
		(function(){
			const initval = $('td.cart-item-row input[type="number"]').val();
			$('td.cart-item-row input[type="number"]').change(function(){
				if ($(this).val() == initval){
					$(this).next().hide();
				}else{
					$(this).next().show();
				}
				
			});
		})();
		$(document).ready(function(){
			$('span.cart-item-update a').click(function(){
				console.log('ah');
				$(this).closest('form').submit();
			});
		});
		
	</script>
{% endblock %}

gomez/templates/gomez/order/subscription_expired_landing_page.html
{% extends "core/base_generic.html" %}

{% load staticfiles %}
{% load gmz_extras %}
{% load prices_i18n %}

{% block head_base_links %}
	{{ block.super }}
{% endblock %}
{% block title %}{{title}}{% endblock %}

{% block container %}
	<div class="small-12 large-12 column kitapp-content">
		{% block content %}
			{% if messages %}
			<div class="alert callout">
				{% for message in messages %}
					<p>{{ message }}</p>
				{% endfor %}
			</div>
			{% endif %}
			<div class="row">
			{% for subsc_product in subscription_products %}
				<div class="column small-12 medium-{% widthratio 12 subscription_products|length 1 %}">
					<table style="text-align: center;">
						<tr>
							<td>{{subsc_product.name|upper}}</td>
						</tr>
						<tr>
							<td>{% gross subsc_product.price %}</td>
						</tr>
						<tr>
							<td>
								{% for plan_line in subsc_product.description|splittolist %}
									<div>{{plan_line|default:"&nbsp;"}}</div>
								{% endfor %}
							</td>
						</tr>
						<tr>
							<td>
								{% if subsc_product.meta.plan_id == request.user.kituser.kitbilling.service_plan.pk %}
									<button class="button renew-button" data-product-id="{{subsc_product.id}}">Renew</button>
								{% else %}
									<button class="button subscribe-button" data-product-id="{{subsc_product.id}}">Subscribe</button>
								{% endif %}
							</td>
						</tr>
					</table>
					
				</div>
			{% endfor %}
			
			</div>
		{% endblock %}
	</div>

{% endblock %}

{% block foot_base_js %}
	{{ block.super }}
	<script type="text/javascript" src="{% static "js/humanize.js" %}"></script>
	<script>
		$("button.renew-button").click(function(e){
			var url = '/order/start/?action=renew&product_id='+$(this).data('product-id');
			window.location = url;
		});
		$("button.subscribe-button").click(function(e){
			var url = '/order/start/?action=resub&product_id='+$(this).data('product-id');
			window.location = url;
		});
	</script>
{% endblock %}